### ISSUE TITLE
Freya nelze spustit na ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by roman-dvorak** [MLAB-project/pysdr#14]
Tuto informaci mám zprostředkovanou. Je potřeba ji ověřit, popř. vyřešit/zaktualizovat návod na wiki.

**Comment by kaklik** [comment]
Tohle už předpokládám neplatí minimálně pro větev 3dwf, kterou by zřejmě chtělo mergnout do master.

**Comment by roman-dvorak** [comment]
Jo, přesně tak.
